apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-staff
  namespace: ems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-staff
  template:
    metadata:
      labels:
        app: postgres-staff
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: staff
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-staff
  namespace: ems
spec:
  selector:
    app: postgres-staff
  ports:
    - port: 5432
      targetPort: 5432