eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
server:
  port: 8070
spring:
  application:
    name: contract
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-contract:5432/contract
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
staff:
  service:
    url: http://staff-service:8060
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://192.168.1.134:9411/api/v2/spans