eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8060
spring:
  application:
    name: staff
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-staff:5432/staff
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://192.168.1.134:9411/api/v2/spans