apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ems
data:
  # Internal URLs within the cluster (Kubernetes DNS)
  EUREKA_URI: "http://eureka:8761/eureka"
  CONFIG_SERVER_URI: "http://config-server:8888"
  KEYCLOAK_URL: "http://host.docker.internal:8082"
  KAFKA_BOOTSTRAP: "192.168.1.134:9092"