apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-side
  namespace: ems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-side
  template:
    metadata:
      labels:
        app: frontend-side
    spec:
      containers:
        - name: frontend-side
          image: sidaouimohamedamine/frontend-side:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-side
  namespace: ems
spec:
  selector:
    app: frontend-side
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP